#! /bin/bash
infname=$1
OUT=` echo $infname | cut -d '.' -f 1 `

usage=" $0 averageimage " 

if [[ ${#img} -lt 1 ]] ; then 
  echo " please set a valid input image - you set $infname "
  echo $usage 
  exit 1
fi 

ants_bxt () {

inname=${infname}
outname=${OUT}
BM=${OUT}_brainmask.nii.gz
ThresholdImage 3 $img $BM Otsu 3
ThresholdImage 3 $BM $BM 2 3 
ImageMath 3 $BM ME $BM 1 
ImageMath 3 $BM GetLargestComponent $BM 
ImageMath 3 $BM MD $BM  1
#  ImageMath 3 $BM ME $BM  1

}

# main 
if [[ -s ${infname} ]] & [[ ${#infname} -gt 3 ]]; 
then 
  ants_bxt ${infname} ${OUT}
else 
  echo $usage
fi 
