#! /bin/bash
FIX=$1
MOV=$2
usefixed=$3
usage=" $0 fixed3d movingtimeseriesimage reference_image_choice " 
if [[ ${#usefixed} -lt 1 ]] ; then 
  echo " do you want to use a fixed reference image \(option 1\) or map time_i+1 to time_i \(option 0\) ?"
  echo $usage 
  exit 1
fi 
OUT=` echo $MOV | cut -d '.' -f 1 `
if [[ -s $FIX ]]  & [[ -s $MOV ]] & [[ ${#FIX} -gt 3 ]]  & [[ ${#MOV} -gt 3 ]]  ; then 
exe="ants_moco -d 3 -o [ ${OUT}MOCO , ${OUT}MOCO.nii.gz , ${OUT}Avg.nii.gz ] \
                        -t Rigid[1.e-1]  \
                         -i 10x5  \
                        -u $usefixed  \
                        -e 1  \
                        -s 1x0  \
                        -f 1x1 \
                        -m MI[ $FIX ,  $MOV , 1, 16, 100 ] "
#                        -m MI[ $FIX ,  $MOV , 1, 32, 1 ] "
#                        -m Demons[ $FIX ,  $MOV , 1, 2] "

echo $exe

$exe
else 
echo usage :  $0 fixed_3d_image moving_time_series_image 
fi 
