#! /bin/bash
img=$1
usage=" $0 timeseriesimage " 
if [[ ${#img} -lt 1 ]] ; then 
  echo " please set a valid input image - you set $img "
  echo $usage 
  exit 1
fi 
OUT=` echo $img | cut -d '.' -f 1 `
if [[ -s $img ]] & [[ ${#img} -gt 3 ]]  ; then 
  avg=${OUT}_avg.nii.gz
  ants_moco -d 3 -a $img -o $avg 
  exe="ants_moco -d 3 -o [ ${OUT} , ${OUT}moco.nii.gz , $avg ]                        
                 -m MI[ $avg , $img , 1, 20, 50 ]                          
                 -t Rigid[0.01]  
                 -i 25  -u 1  -e 1  -s 0  -f 1  -n 10 "
  $exe
# non rigid template based on 4 images  
  exe="ants_moco -d 3 -o [ ${OUT} , ${OUT}moco.nii.gz , $avg]                         
                 -m MI[ $avg , $img , 1, 20, 50 ]                          
                 -t Rigid[0.01]  
                 -i 25  -u 1  -e 1  -s 0  -f 1  -n 10 
                 -m CC[ $fix ,  $MOV , 1, 2 ]                          
                 -t GaussianDisplacementField[0.15 , 3, 0.5 ]   
                 -i 10  -u 1  -e 1  -s 0  -f 1 -n 10 "
  $exe
else 
echo $usage
fi 
