#! /bin/bash
imgmoco=$1
imgbrainmask=$2
imgavg=$3 
analysishome=$4
usage=" $0 moco-image brain-mask " 
if [[ ${#imgmoco} -lt 1 ]] ; then 
  echo " please set a valid moco image - you set $imgmoco "
  echo $usage 
  exit 1
fi 
if [[ ${#imgbrainmask} -lt 1 ]] ; then 
  echo " please set a valid brain mask image - you set $imgbrainmask "
  echo $usage 
  exit 1
fi 
if [[ ${#imgavg} -lt 1 ]] ; then 
  echo " please set a valid average image - you set $imgavg "
  echo $usage 
  exit 1
fi 
if [[ ${#analysishome} -lt 1 ]] ; then 
  echo " please set a valid home path for the analysis package - you set $analysishome "
  echo $usage 
  exit 1
fi 
OUT=` echo $imgmoco | cut -d '.' -f 1 `
mocoparams=` ls ${OUT:0:${#OUT}-5}*MOCOparams.csv `
 ImageMath 4 ${OUT}_compcorr.nii.gz CompCorrAuto $imgmoco $imgbrainmask 6
 N3BiasFieldCorrection 3 $imgavg $imgavg 2 $imgbrainmask 
 for x in 1 2 3 ; do N3BiasFieldCorrection 3 $imgavg $imgavg 1 $imgbrainmask ; done
 Atropos -d 3 -a $imgavg -a ${OUT}_compcorr_variance.nii.gz -m [0.3,1x1x1] -o ${OUT}_seg.nii.gz -c [5,0] -i kmeans[3] -x $imgbrainmask 
 ThresholdImage 3 ${OUT}_seg.nii.gz ${OUT}_cortmask.nii.gz 2 2
 sccan  --timeseriesimage-to-matrix [$imgmoco,${OUT}_cortmask.nii.gz, 0.0 , 0.0 ] -o ${OUT}.csv
# parcellate the image
Rscript ${analysishome}statistics/antsr_frequency_filter.R ${OUT}.csv ${OUT}_filt.csv $tr 0.02 0.06 ${OUT}_compcorr_compcorr.csv  
 sccan  --sparse-svd [${OUT}.csv,${OUT}_cortmask.nii.gz,-0.15,${OUT}_compcorr_compcorr.csv] -n 40 -i 40 --PClusterThresh 50  -o ${OUT}_RSF_Networks.nii.gz   --partial-scca-option PminusRQ
tr=1.5
Rscript ${analysishome}statistics/antsr_frequency_filter.R ${OUT}_RSF_NetworksprojectionsView1vec.csv ${OUT}_filt.csv $tr 0.02 0.06 ${OUT}_compcorr_compcorr.csv  
# sccan  --sparse-svd [${OUT}.csv,${OUT}_cortmask.nii.gz,0.9] -n 20 -i 40 --PClusterThresh 200  -o ${OUT}_RSF_Networks.nii.gz 
# 
Rscript  ${analysishome}/statistics/antsr_resting_state_corr_eigenanat.R ${OUT}_ea_rsf ${OUT}_filt.csv ${OUT}_filt.csv  ${OUT}_compcorr_compcorr.csv  $mocoparams
