#! /bin/bash
imgmoco=$1
imgbrainmask=$2
imgavg=$3 
analysishome=$4
usage=" $0 moco-image brain-mask " 
if [[ ${#imgmoco} -lt 1 ]] ; then 
  echo " please set a valid moco image - you set $imgmoco "
  echo $usage 
  exit 1
fi 
if [[ ${#imgbrainmask} -lt 1 ]] ; then 
  echo " please set a valid brain mask image - you set $imgbrainmask "
  echo $usage 
  exit 1
fi 
if [[ ${#imgavg} -lt 1 ]] ; then 
  echo " please set a valid average image - you set $imgavg "
  echo $usage 
  exit 1
fi 
if [[ ${#analysishome} -lt 1 ]] ; then 
  echo " please set a valid home path for the analysis package - you set $analysishome "
  echo $usage 
  exit 1
fi 
OUT=` echo $imgmoco | cut -d '.' -f 1 `
ImageMath 4 ${OUT}_compcorr.nii.gz CompCorrAuto $imgmoco $imgbrainmask 6
N3BiasFieldCorrection 3 $imgavg $imgavg 2 $imgbrainmask 
for x in 1 2 3 ; do N3BiasFieldCorrection 3 $imgavg $imgavg 1 $imgbrainmask ; done
  Atropos -d 3 -a $imgavg -a ${OUT}_compcorr_variance.nii.gz -m [0.3,1x1x1] -o ${OUT}_seg.nii.gz -c [5,0] -i kmeans[3] -x $imgbrainmask 
ThresholdImage 3 ${OUT}_seg.nii.gz ${OUT}_cortmask.nii.gz 2 2
~/code/sccan/bin/sccan  --timeseriesimage-to-matrix [${OUT}_compcorr_corrected.nii.gz,${OUT}_cortmask.nii.gz, 6.0 , 3.0 ] -o ${OUT}.csv
~/code/sccan/bin/sccan  --sparse-svd [${OUT}.csv,${OUT}_cortmask.nii.gz,0.9] -n 40 -i 40 --PClusterThresh 100  -o ${OUT}_RSF_Networks.nii.gz 
# sccan  --sparse-svd [${OUT}.csv,${OUT}_cortmask.nii.gz,-0.1] -n 20 -i 40 --PClusterThresh 20  -o ${OUT}_RSF_Networks.nii.gz 
Rscript  ${analysishome}/statistics/antsr_resting_state_corr_eigenanat.R ${OUT}_ea_rsf ${OUT}_RSF_NetworksprojectionsView1vec.csv ${OUT}_RSF_NetworksprojectionsView1vec.csv  ${OUT}_compcorr_compcorr.csv 
